apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/aminebaha/argoservices.git
    path: microservice1
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true